/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.mailbox.sync.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Mailbox service. Represents a row in the &quot;MailboxSync_Mailbox&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.mailbox.sync.model.impl.MailboxModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.mailbox.sync.model.impl.MailboxImpl}.
 * </p>
 *
 * @author Claus Reitmeier
 * @see Mailbox
 * @see at.mailbox.sync.model.impl.MailboxImpl
 * @see at.mailbox.sync.model.impl.MailboxModelImpl
 * @generated
 */
public interface MailboxModel extends BaseModel<Mailbox>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mailbox model instance should use the {@link Mailbox} interface instead.
	 */

	/**
	 * Returns the primary key of this mailbox.
	 *
	 * @return the primary key of this mailbox
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mailbox.
	 *
	 * @param primaryKey the primary key of this mailbox
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mailbox ID of this mailbox.
	 *
	 * @return the mailbox ID of this mailbox
	 */
	public long getMailboxId();

	/**
	 * Sets the mailbox ID of this mailbox.
	 *
	 * @param mailboxId the mailbox ID of this mailbox
	 */
	public void setMailboxId(long mailboxId);

	/**
	 * Returns the group ID of this mailbox.
	 *
	 * @return the group ID of this mailbox
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this mailbox.
	 *
	 * @param groupId the group ID of this mailbox
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this mailbox.
	 *
	 * @return the company ID of this mailbox
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this mailbox.
	 *
	 * @param companyId the company ID of this mailbox
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this mailbox.
	 *
	 * @return the user ID of this mailbox
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this mailbox.
	 *
	 * @param userId the user ID of this mailbox
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this mailbox.
	 *
	 * @return the user uuid of this mailbox
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this mailbox.
	 *
	 * @param userUuid the user uuid of this mailbox
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this mailbox.
	 *
	 * @return the user name of this mailbox
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this mailbox.
	 *
	 * @param userName the user name of this mailbox
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this mailbox.
	 *
	 * @return the create date of this mailbox
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this mailbox.
	 *
	 * @param createDate the create date of this mailbox
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this mailbox.
	 *
	 * @return the modified date of this mailbox
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this mailbox.
	 *
	 * @param modifiedDate the modified date of this mailbox
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the description of this mailbox.
	 *
	 * @return the description of this mailbox
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this mailbox.
	 *
	 * @param description the description of this mailbox
	 */
	public void setDescription(String description);

	/**
	 * Returns the host of this mailbox.
	 *
	 * @return the host of this mailbox
	 */
	@AutoEscape
	public String getHost();

	/**
	 * Sets the host of this mailbox.
	 *
	 * @param host the host of this mailbox
	 */
	public void setHost(String host);

	/**
	 * Returns the port of this mailbox.
	 *
	 * @return the port of this mailbox
	 */
	public int getPort();

	/**
	 * Sets the port of this mailbox.
	 *
	 * @param port the port of this mailbox
	 */
	public void setPort(int port);

	/**
	 * Returns the mailbox user of this mailbox.
	 *
	 * @return the mailbox user of this mailbox
	 */
	@AutoEscape
	public String getMailboxUser();

	/**
	 * Sets the mailbox user of this mailbox.
	 *
	 * @param mailboxUser the mailbox user of this mailbox
	 */
	public void setMailboxUser(String mailboxUser);

	/**
	 * Returns the mailbox user secret of this mailbox.
	 *
	 * @return the mailbox user secret of this mailbox
	 */
	@AutoEscape
	public String getMailboxUserSecret();

	/**
	 * Sets the mailbox user secret of this mailbox.
	 *
	 * @param mailboxUserSecret the mailbox user secret of this mailbox
	 */
	public void setMailboxUserSecret(String mailboxUserSecret);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(at.mailbox.sync.model.Mailbox mailbox);

	@Override
	public int hashCode();

	@Override
	public CacheModel<at.mailbox.sync.model.Mailbox> toCacheModel();

	@Override
	public at.mailbox.sync.model.Mailbox toEscapedModel();

	@Override
	public at.mailbox.sync.model.Mailbox toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}