package at.mailbox.sync.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Task service. Represents a row in the &quot;MailboxSync_Task&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.mailbox.sync.model.impl.TaskModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.mailbox.sync.model.impl.TaskImpl}.
 * </p>
 *
 * @author Claus Reitmeier
 * @see Task
 * @see at.mailbox.sync.model.impl.TaskImpl
 * @see at.mailbox.sync.model.impl.TaskModelImpl
 * @generated
 */
public interface TaskModel extends BaseModel<Task>, GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a task model instance should use the {@link Task} interface instead.
     */

    /**
     * Returns the primary key of this task.
     *
     * @return the primary key of this task
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this task.
     *
     * @param primaryKey the primary key of this task
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the task ID of this task.
     *
     * @return the task ID of this task
     */
    public long getTaskId();

    /**
     * Sets the task ID of this task.
     *
     * @param taskId the task ID of this task
     */
    public void setTaskId(long taskId);

    /**
     * Returns the group ID of this task.
     *
     * @return the group ID of this task
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this task.
     *
     * @param groupId the group ID of this task
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this task.
     *
     * @return the company ID of this task
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this task.
     *
     * @param companyId the company ID of this task
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this task.
     *
     * @return the user ID of this task
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this task.
     *
     * @param userId the user ID of this task
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this task.
     *
     * @return the user uuid of this task
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this task.
     *
     * @param userUuid the user uuid of this task
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this task.
     *
     * @return the user name of this task
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this task.
     *
     * @param userName the user name of this task
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this task.
     *
     * @return the create date of this task
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this task.
     *
     * @param createDate the create date of this task
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this task.
     *
     * @return the modified date of this task
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this task.
     *
     * @param modifiedDate the modified date of this task
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the status of this task.
     *
     * @return the status of this task
     */
    @AutoEscape
    public String getStatus();

    /**
     * Sets the status of this task.
     *
     * @param status the status of this task
     */
    public void setStatus(String status);

    /**
     * Returns the description of this task.
     *
     * @return the description of this task
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this task.
     *
     * @param description the description of this task
     */
    public void setDescription(String description);

    /**
     * Returns the mailbox ID of this task.
     *
     * @return the mailbox ID of this task
     */
    public long getMailboxId();

    /**
     * Sets the mailbox ID of this task.
     *
     * @param mailboxId the mailbox ID of this task
     */
    public void setMailboxId(long mailboxId);

    /**
     * Returns the permission user group ID of this task.
     *
     * @return the permission user group ID of this task
     */
    public long getPermissionUserGroupId();

    /**
     * Sets the permission user group ID of this task.
     *
     * @param permissionUserGroupId the permission user group ID of this task
     */
    public void setPermissionUserGroupId(long permissionUserGroupId);

    /**
     * Returns the event calendar ID of this task.
     *
     * @return the event calendar ID of this task
     */
    public long getEventCalendarId();

    /**
     * Sets the event calendar ID of this task.
     *
     * @param eventCalendarId the event calendar ID of this task
     */
    public void setEventCalendarId(long eventCalendarId);

    /**
     * Returns the document folder ID of this task.
     *
     * @return the document folder ID of this task
     */
    public long getDocumentFolderId();

    /**
     * Sets the document folder ID of this task.
     *
     * @param documentFolderId the document folder ID of this task
     */
    public void setDocumentFolderId(long documentFolderId);

    /**
     * Returns the webcontent folder ID of this task.
     *
     * @return the webcontent folder ID of this task
     */
    public long getWebcontentFolderId();

    /**
     * Sets the webcontent folder ID of this task.
     *
     * @param webcontentFolderId the webcontent folder ID of this task
     */
    public void setWebcontentFolderId(long webcontentFolderId);

    /**
     * Returns the vocabulary ID of this task.
     *
     * @return the vocabulary ID of this task
     */
    public long getVocabularyId();

    /**
     * Sets the vocabulary ID of this task.
     *
     * @param vocabularyId the vocabulary ID of this task
     */
    public void setVocabularyId(long vocabularyId);

    /**
     * Returns the period of this task.
     *
     * @return the period of this task
     */
    public long getPeriod();

    /**
     * Sets the period of this task.
     *
     * @param period the period of this task
     */
    public void setPeriod(long period);

    /**
     * Returns the clamav server i p of this task.
     *
     * @return the clamav server i p of this task
     */
    @AutoEscape
    public String getClamavServerIP();

    /**
     * Sets the clamav server i p of this task.
     *
     * @param clamavServerIP the clamav server i p of this task
     */
    public void setClamavServerIP(String clamavServerIP);

    /**
     * Returns the clamav port of this task.
     *
     * @return the clamav port of this task
     */
    public int getClamavPort();

    /**
     * Sets the clamav port of this task.
     *
     * @param clamavPort the clamav port of this task
     */
    public void setClamavPort(int clamavPort);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(at.mailbox.sync.model.Task task);

    @Override
    public int hashCode();

    @Override
    public CacheModel<at.mailbox.sync.model.Task> toCacheModel();

    @Override
    public at.mailbox.sync.model.Task toEscapedModel();

    @Override
    public at.mailbox.sync.model.Task toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
