package at.mailbox.sync.model.impl;

import at.mailbox.sync.model.Task;
import at.mailbox.sync.service.TaskLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Task service. Represents a row in the &quot;MailboxSync_Task&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaskImpl}.
 * </p>
 *
 * @author Claus Reitmeier
 * @see TaskImpl
 * @see at.mailbox.sync.model.Task
 * @generated
 */
public abstract class TaskBaseImpl extends TaskModelImpl implements Task {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a task model instance should use the {@link Task} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TaskLocalServiceUtil.addTask(this);
        } else {
            TaskLocalServiceUtil.updateTask(this);
        }
    }
}
